### ISSUE TITLE
responses of kprime questions are changed when restoring a coursebackup

### ISSUE THREAD

**Issue by isacsonk** [ndunand/moodle-qtype_matrix#23] opened 2014-09-16 08:13 UTC
## how to reproduce

1) create as admin or teacher a course with a test with some kprime questions. Do not change the labels for the responses. Leave them to true and then false.
2) as a student do the test
3) as an admin backup the whole course
4) as an admin restore the whole course into a new course
--> if you as a teacher preview the test, you'll see that now you have first false then true as response labels. 
## Requirement

backup and restoring should not change the order of the response labels
## Remark

The responses of the students are still correct. Also the correct options are still marked correctly. The whole columns true and false were switched.

**Comment by laurentopprecht** [comment] 2015-08-13 09:11
Unable to reproduce. Seems to be fixed by #19. Need to be tested

**Comment by NicoAlexH** [comment] 2022-12-15 14:36
Couldn't reproduce this bug, I'm closing this issue for now but feel free to reopen it if needed

**Closed by NicoAlexH** 2022-12-15 14:36 UTC
