### ISSUE TITLE
export as XML not functional

### ISSUE THREAD

**Issue by ndunand** [ndunand/moodle-qtype_matrix#50] opened 2020-08-12 16:05 UTC
export as Moodle XML contains question text but not question items.

**Comment by NicoAlexH** [comment] 2022-12-14 15:23
Cannot reproduce, data seems to be fully exported ; closing this issue for now

**Closed by NicoAlexH** 2022-12-14 15:23 UTC
Labels: bug, Priority 1

**Comment by a-kempka** [comment] 2025-01-30 09:53
When question items contain HTML and especially when exporting multiple questions the items only contain "Array" (See #65)
